### ISSUE TITLE
opensupports v.4.9 working in docker but not standalone

### ISSUE THREAD

**Issue by linolano** [gamelaster/opensupports-docker#2]
Hi,
I tried your docker installation and it works just fine.
I then repated the same steps as your dockerfile's in a standalone apache2 installation but I get an error whenever I try the test SMTP connection.
Can you explain why?
Thanks and regards

**Comment by gamelaster** [comment]
Hi, what kind of error?

**Comment by linolano** [comment]
after pushing the button Test SMTP Connection, the loader keeps spinning forever and this is written in the Chrome Console:
bundle.js:16 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'showCloseButton')

basically, I reproduced your steps in the dockerfile except for fix-https-reverse-proxy.diff:

sudo apt-get update
sudo apt-get install apache2
config apacha2:
```
<VirtualHost *:80>
  ServerName localhost
  DocumentRoot "/var/www/html"
  Options Indexes FollowSymLinks
  <Directory "/var/www/html">
    AllowOverride All
    Require all granted
 </Directory>
</VirtualHost>
```
sudo a2enmod rewrite
sudo apt install php libapache2-mod-php
sudo apt install mysql-server php-mysql
sudo systemctl restart apache2

then I downloaded https://github.com/opensupports/opensupports/releases/download/v4.9.0/opensupports_v4.9.0.zip and unzip in /var/www/html
the application runs at http://localhost/install but the server response to the SMTP test is "undefined":

`bundle.js:16 Uncaught (in promise) TypeError: Cannot read properties of **undefined** (reading 'showCloseButton')`

I also tried to install Postfix (sudo apt install mailutils) and send an email from my local system and everything works. The very weird thing is that your docker installation also works fine.
