### ISSUE TITLE
Missing PHP-Module imap

### ISSUE THREAD

**Issue by klenzel** [gamelaster/opensupports-docker#4]
When trying to trigger the IMAP-Polling, it results in following error:

`{"status":"fail","message":"Use of undefined constant SE_UID - assumed 'SE_UID' (this will throw an Error in a future version of PHP)","data":null}`

Would it be possible, that the PHP-Module "imap.so" is missing?

`root@OS-Container:/usr/local/etc/php/conf.d# php -m | grep imap`
-Nothing found-

`root@OS-Container:/usr/local/etc/php/conf.d# ls /usr/local/etc/php/conf.d
docker-php-ext-mysqli.ini  docker-php-ext-pdo_mysql.ini  docker-php-ext-sodium.ini  timezone.ini`

See also
https://github.com/barbushin/php-imap/issues/260

**Comment by gamelaster** [comment]
Should be working now. Thanks and sorry for late reply.
